
dahouet_Accueil:
    path:     /Accueil
    defaults: { _controller: "DahouetMainBundle:Main:index" }
    
Connexion:
    path:       /Connexion
    defaults:   { _controller: "DahouetMainBundle:Connexion:index" }
    
Deconnexion:
    path:       /Deconnexion
    defaults:   { _controller: "DahouetMainBundle:Deconnexion:index" }
    
InscriptionRegate:
    path:       /InscriptionRegate
    defaults:   { _controller: "DahouetMainBundle:InscriptionRegate:index" }
    
validVoilier:
    path:       /validVoilier
    defaults:   { _controller: "DahouetMainBundle:validVoilier:index" }
    